# Generated by Django 2.2.6 on 2019-10-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Camas',
            new_name='Cama',
        ),
    ]
